part of '../terminal/terminal.dart';

/// A keyboard input event containing physical key information, modifiers, and
/// generated text for terminal key encoding.
///
/// Set the event properties and pass it to [KeyEncoder.encode] to produce a
/// terminal escape sequence. Events can be reused across multiple
/// [KeyEncoder.encode] calls by changing their properties between calls.
///
/// Throws [OutOfMemoryException] if the native allocation fails during
/// construction.
///
/// ```dart
/// final event = KeyEvent()
///   ..action = KeyAction.press
///   ..key = Key.c
///   ..mods = Mods.ctrl();
///
/// final seq = encoder.encode(event);
/// if (seq.isNotEmpty) pty.write(utf8.encode(seq));
///
/// event.dispose();
/// ```
final class KeyEvent {
  static final _finalizer = Finalizer(bindings.key.keyEventFree);

  final LibGhosttyHandle _handle;
  var _disposed = false;

  /// Creates a new key event with default values.
  ///
  /// Set the event properties ([action], [key], [mods], etc.) before passing
  /// to [KeyEncoder.encode]. Events can be reused by changing their properties
  /// between encode calls.
  ///
  /// Throws [OutOfMemoryException] if the native allocation fails.
  KeyEvent() : _handle = bindings.key.keyEventNew() {
    _finalizer.attach(this, _handle, detach: this);
  }

  /// The key action: [KeyAction.press], [KeyAction.release], or
  /// [KeyAction.repeat].
  KeyAction get action {
    final handle = _requireHandle();
    return bindings.key.keyEventGetAction(handle);
  }

  /// Sets the key action (press, release, repeat).
  set action(KeyAction value) {
    final handle = _requireHandle();
    bindings.key.keyEventSetAction(handle, value);
  }

  /// Whether this event is part of a composition sequence (e.g. dead keys,
  /// IME input).
  bool get composing {
    final handle = _requireHandle();
    return bindings.key.keyEventGetComposing(handle);
  }

  /// Sets whether this event is part of a composition sequence.
  set composing(bool value) {
    final handle = _requireHandle();
    bindings.key.keyEventSetComposing(handle, composing: value);
  }

  /// Modifiers consumed by the platform during key processing.
  ///
  /// For example, Shift is consumed when producing an uppercase letter. The
  /// encoder uses this to avoid double-reporting modifiers that the platform
  /// already handled.
  Mods get consumedMods {
    final handle = _requireHandle();
    return Mods.fromValue(bindings.key.keyEventGetConsumedMods(handle));
  }

  /// Sets the consumed modifiers bitmask.
  set consumedMods(Mods value) {
    final handle = _requireHandle();
    bindings.key.keyEventSetConsumedMods(handle, value.value);
  }

  /// Physical, layout-independent key code based on the W3C UI Events
  /// KeyboardEvent code standard.
  ///
  /// Represents the physical key position, not the character it produces. For
  /// example, [Key.a] on a US keyboard and the equivalent position on a
  /// Russian keyboard both report the same key code. Layout-dependent text is
  /// provided separately via [utf8].
  Key get key {
    final handle = _requireHandle();
    return bindings.key.keyEventGetKey(handle);
  }

  /// Sets the physical key code.
  set key(Key value) {
    final handle = _requireHandle();
    bindings.key.keyEventSetKey(handle, value);
  }

  /// Active modifier keys at the time of the event.
  Mods get mods {
    final handle = _requireHandle();
    return Mods.fromValue(bindings.key.keyEventGetMods(handle));
  }

  /// Sets the modifier keys bitmask.
  set mods(Mods value) {
    final handle = _requireHandle();
    bindings.key.keyEventSetMods(handle, value.value);
  }

  /// Unicode codepoint for this key without Shift applied.
  int get unshiftedCodepoint {
    final handle = _requireHandle();
    return bindings.key.keyEventGetUnshiftedCodepoint(handle);
  }

  /// Sets the unshifted Unicode codepoint.
  set unshiftedCodepoint(int value) {
    final handle = _requireHandle();
    bindings.key.keyEventSetUnshiftedCodepoint(handle, value);
  }

  /// UTF-8 text generated by the keyboard layout for this key.
  ///
  /// Returns null when no text is set. The returned string is a Dart-owned
  /// snapshot and remains valid after the event is modified or disposed.
  String? get utf8 {
    final handle = _requireHandle();
    return bindings.key.keyEventGetUtf8(handle);
  }

  /// Sets the UTF-8 text generated by the keyboard layout for this key, or
  /// null to clear it.
  ///
  /// Must contain the unmodified character before any Ctrl/Meta
  /// transformations. The encoder derives modifier sequences from the logical
  /// [key] and [mods] bitmask, not from this text.
  ///
  /// Do not pass C0 control characters (U+0000-U+001F, U+007F) or platform
  /// function key codes (e.g. macOS PUA U+F700-U+F8FF); pass null instead and
  /// let the encoder use the logical key.
  ///
  /// The string is copied into the event.
  set utf8(String? value) {
    final handle = _requireHandle();
    bindings.key.keyEventSetUtf8(handle, value);
  }

  /// Releases the native key event handle.
  ///
  /// Calling [dispose] more than once is safe. Every other member throws a
  /// [StateError] after disposal.
  void dispose() {
    if (_disposed) return;
    bindings.key.keyEventFree(_handle);
    _finalizer.detach(this);
    _disposed = true;
  }

  LibGhosttyHandle _requireHandle() {
    if (_disposed) throw StateError('KeyEvent has been disposed');
    return _handle;
  }
}
